version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "4001:4001"
    volumes: 
      - ./:/app
      - /app/node_modules/

  postgres:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    volumes: 
      - pgdata:/var/lib/postgresql/data
volumes: 
  postgresdata: